name: Test

on:
  push:
    branches:
      - '*'
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load .env
        uses: falti/dotenv-action@v1.0.4
        with:
          export-variables: true
          log-variables: true
          keys-case: upper

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run lints
        uses: reviewdog/action-eslint@v1.23.0
        with:
          reporter: github-check
          fail_on_error: true
          eslint_flags: src

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load .env
        uses: falti/dotenv-action@v1.0.4
        with:
          export-variables: true
          log-variables: true
          keys-case: upper

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Report coverage
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: yarn run test
          coverage-comment: false

  format:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check formatting
        uses: dprint/check@v2.2

  image:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
      - format
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load .env
        uses: falti/dotenv-action@v1.1
        with:
          export-variables: true
          log-variables: true
          keys-case: upper

      - name: Login to GHCR
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Extract metadata
        id: metadata
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3.2.0

      - name: Build & push image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: Containerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          build-args: |
            NODE_VERSION=${{ env.NODE_VERSION }}
